version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: loan_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Python#321
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: loan_management_db
      DB_USER: postgres
      DB_PASSWORD: Python#321
      DB_HOST: db
      DB_PORT: 5432
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
