# Generated by Django 5.1.4 on 2025-06-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='monthly_salary',
            new_name='monthly_income',
        ),
    ]
